 language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    oprganization: "JokeyF"
    token: "1647adc231ffa65699d256e730bc64189489a83a"
    
script:
- cd HelloWorldProject
- ant build
- sonar-scanner