 language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    oprganization: "giordanospirito"
    token: "756de6987dde4e1cedfc1e9477208f8f4ea55694"
    
script:
- cd HelloWorldProject
- ant build
- sonar-scanner