 language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    oprganization: "jokeyf"
    token: "54906916b3e95ad6c0ee61db873630822117dfab"
    
script:
- cd HelloWorldProject
- ant build
- sonar-scanner